### create template
POST {{baseUrl}}/api/box
Content-Type: application/json

{
  "payload": {
    "service": "widget-x",
    "stage": {
      "development": {
        "template": {
          "name": "task_definition.json",
          "value": "{\"ENV_1\":\"{widget-x.development.key}\",\"ENV_2\":\"{widget-x.development.debug}\",\"GLOBAL_SERVICE\":\"{widget-x.sentry}\",\"domain\":\"{private-domain}\"}"
        }
      }
    }
  }
}


### get all boxes
GET {{baseUrl}}/api/box
Content-Type: application/json


### check exist template
HEAD {{baseUrl}}/api/box/widget-x/development/task_definition.json
Content-Type: application/json


### get template
GET {{baseUrl}}/api/box/widget-x/development/task_definition.json
Content-Type: application/json


### build template
GET {{baseUrl}}/api/box/widget-x/development/task_definition.json/build
Content-Type: application/json


### create
POST {{baseUrl}}/api/entry
Content-Type: application/json

[
  {"key": "widget-x/development/debug", "value": "False"},
  {"key": "widget-x/development/key", "value": "bla bla 2"},
  {"key": "widget-x/development/domain", "value": "test.com"},
  {"key": "widget-x.sentry", "value": "xxxxx secret sentry"},
  {"key": "private-domain", "value": "privatedomain"}
]


### Get key
GET {{baseUrl}}/api/entry/key?v=widget-x/development/domain
Content-Type: application/json


### Get prefix
GET {{baseUrl}}/api/entry/prefix?v=widget-x/development
Content-Type: application/json
