### create
POST http://localhost:8090/api/
Content-Type: application/json

{
  "service": "demo1",
  "stages": {
    "development": null,
    "qa": null
  }
}


### upsert variables api/:service/
# commands
# ${stage}.upsert.variables
# ${stage}.upsert.template
PUT http://localhost:8090/api/box/demo1
Content-Type: application/json

{
  "command": "upsert.variables",
  "stage": "development",
  "payload": {
    "key": "NORLIS",
    "value": "hola"
  }
}

### upsert template api/:service/

PUT http://localhost:8090/api/box/demo1
Content-Type: application/json

{
  "command": "upsert.template",
  "stage": "development",
  "payload": {
    "value": "{\"blabla\": \"value\"}"
  }
}


### create service

POST http://localhost:7337/api/box
Content-Type: application/json

{
  "command": "create.service",
  "stage": "development",
  "payload": {
    "service": "widget-x",
    "stage": {
      "development": {
        "template": {
          "name": "task_definition.json",
          "value": "{\"key\": \"value\"}",
          "Version": 0,
          "CreatedTime": "0001-01-01T00:00:00Z"
        },
        "variables": {
          "AGE": {
            "value": 100,
            "Version": 0,
            "CreatedTime": "0001-01-01T00:00:00Z"
          },
          "NAME": {
            "value": "n1",
            "Version": 0,
            "CreatedTime": "0001-01-01T00:00:00Z"
          }
        }
      }
    }
  }
}


### create
POST http://localhost:7337/api/entry
Content-Type: application/json

[
  {"key": "argos/development/debug", "value": "False"},
  {"key": "argos/development/django_settings_module", "value": "config.settings.production"}
]


### Get key
GET http://localhost:7337/api/entry/key?v=argos/test/user3
Content-Type: application/json


### Get prefix
GET http://localhost:7337/api/entry/prefix?v=argos/qa
Content-Type: application/json
