### create template
POST {{baseUrl}}/api/box
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json

{
  "payload": {
    "service": "widget-x",
    "stage": {
      "development": {
        "template": {
          "name": "task_definition.json",
          "value": "ewogICAiRU5WXzEiOiAie3dpZGdldC14LmRldmVsb3BtZW50LmtleX0iLAogICAiRU5WXzIiOiAie3dpZGdldC14LmRldmVsb3BtZW50LmRlYnVnfSIsCiAgICJHTE9CQUxfU0VSVklDRSI6ICJ7d2lkZ2V0LXguc2VudHJ5fSIsCiAgICJkb21haW4iOiAie3ByaXZhdGUtZG9tYWlufSIsCiAgICJ2ZXJzaW9uIjogIjEiCn0K"
        }
      }
    }
  }
}


### get all boxes
GET {{baseUrl}}/api/box
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json


### check exist template
HEAD {{baseUrl}}/api/box/widget-x/development/task_definition.json
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json


### get template
GET {{baseUrl}}/api/box/widget-x/development/task_definition.json
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json


### build template
GET {{baseUrl}}/api/box/widget-x/development/task_definition.json/build
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json


### create
POST {{baseUrl}}/api/entry
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json

[
  {"key": "widget-x/development/debug", "value": "False"},
  {"key": "widget-x/development/key", "value": "bla bla 2"},
  {"key": "widget-x/development/domain", "value": "test.com"},
  {"key": "widget-x.sentry", "value": "xxxxx secret sentry"},
  {"key": "private-domain", "value": "privatedomain"},
  {"key": "widget-x/development2/debug", "value": "False"},
  {"key": "widget-x/development2/key", "value": "bla bla 2"},
  {"key": "widget-x/development2/domain", "value": "test.com"}
]


### testing create
POST {{baseUrl}}/api/entry
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json

[
  {
    "key": "widget-x/development3/debug",
    "value": "False"
  },
  {
    "key": "widget-x/development3/key",
    "value": "bla bla 2"
  },
  {
    "key": "widget-x/development3/domain",
    "value": "test.com",
    "secure": true
  },
  {
    "key": "widget-x/development3/api-key",
    "value": "qwertyuiopsdfghjklzxcvbnm",
    "secure": true
  }
]


### Get key
GET {{baseUrl}}/api/entry/key?v=widget-x/development/domain
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json


### Get prefix
GET {{baseUrl}}/api/entry/prefix?v=widget-x/development3
Content-Type: application/json
Authorization: Basic {{user}} {{pass}}


### list tracking history
GET {{baseUrl}}/api/tracking/key?v=widget-x/development3/domain
Content-Type: application/json
Authorization: Basic {{user}} {{pass}}


### Delete key
DELETE {{baseUrl}}/api/entry/key?v=widget-x/development3
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json
